CREATE TABLE `READINGS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TIME` BIGINT UNSIGNED NOT NULL,
  `SENSOR_ID` INT(5) UNSIGNED NOT NULL,
  `VALUE` DOUBLE(10,5) NOT NULL,
  PRIMARY KEY (`ID`)
);


CREATE TABLE `SENSORS` (
  `SENSOR_ID` INT(5) UNSIGNED UNIQUE NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  `UNIT` VARCHAR(50),
  PRIMARY KEY (`SENSOR_ID`)
);